name: secrets and env's Pipeline

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true

env:
  MY_SECRET: ${{ secrets.MY_SECRET }}
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Print Envionment variables
      run: |
        echo "MY_SECRET: $MY_SECRET"
        echo "NODE_ENV: $NODE_ENV"

    - name: Run shell Command
      run: |
        echo "Run Successful"
